version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=JEnKins542s
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    image: godgiven123/test_comments-backend:latest
    ports:
      - "7092:7092"
    environment:
      - ASPNETCORE_URLS=http://+:7092
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Test_Comments;User Id=sa;Password=JEnKins542s;Encrypt=False;TrustServerCertificate=True
    networks:
      - app-network
    depends_on:
      - sqlserver

  frontend:
    image: godgiven123/test_comments-frontend:latest
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
